"$schema" = 'https://starship.rs/config-schema.json'

add_newline = true

format = '''
($cmd_duration)
$username $hostname \($os\)$linebreak
$directory($git_branch $dotnet)$linebreak
$character'''

[username]
disabled=false
show_always=true
format="[$user](#e5c890 bold)"

[hostname]
ssh_only=false
disabled=false
format="[on $hostname](#ca9ee6 bold)"

[os]
disabled=false
format="[($name)](#8caaee)"

[dotnet]
style='#ca9ee6'

[git_branch]
style='#F1502F'

[directory]
style='#ef9f76 bold'
